name: 🚀🚀 Basic 👨‍💻Dev - Sec🪲 Ops📉  Workflow 🚀🚀  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Workflow
      run: echo "✅ Dummy Step, compile, package, create container for application and ..."

#  test:
 #   runs-on: ubuntu-latest
  #  needs: build
    
    # ... all others test

    # SAST Test
   # steps:
    #- name: Checkout
     # uses: actions/checkout@v2

   # - name: SAST
    #  run: |
     #   env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
      #  docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
       # docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
    
  deploy:
    runs-on: ubuntu-latest
    needs: test

      # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    - name: Azure Login
      uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
            
      # Runs a set of commands using the runners shell
      - name: Deploy the App
        uses: Azure/cli@v1.0.7
        with:
          azcliversion: 2.30.0
          inlineScript: | 
            az group create -n "${{ vars.AZ_ACI_DNS_PREFIX }}-rg" -l eastus
            az container create --name "${{ vars.AZ_ACI_DNS_PREFIX }}" --dns-name-label "${{ vars.AZ_ACI_DNS_PREFIX }}" --image vulnerables/web-dvwa -g "${{ vars.AZ_ACI_DNS_PREFIX }}-rg"
            
 # dast:
  #  runs-on: ubuntu-latest
   # needs: deploy

   # steps:
   # - name: DAST analysis
    #  run: |
    #    echo "🏗️ Runing DAST Analysis"
